'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { apiFetch } from '@/lib/api/client';
import { useDashboardSession } from '@/components/dashboard/session';
import { useWorkflowMutation } from '@/hooks/useWorkflowMutation';
import { useDraftProtection } from '@/hooks/useDraftProtection';
import { EntityPicker, type BusinessEntity } from '@/components/shared/EntityPicker';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { toast } from 'sonner';
type Detail = { id: string; reference_no: string; status: string; service_type: string; branch: BusinessEntity; warehouse: BusinessEntity | null; customer: BusinessEntity | null; serial: { serialNumber: string; status: string } | null; issue: string; intake_condition?: string; accessories?: string; estimated_amount: string; approved_amount?: string; deposit_required: string; warranty_eligible: boolean; received_at: string; delivered_at?: string; available_transitions: string[]; service_sale: { id: string; referenceNo: string } | null; approval: { id: string; status: string; requestedBy: string } | null;
  parts: { id: string; product: BusinessEntity; quantity: string; unit_cost: string; unit_price: string; warranty_covered: boolean }[];
  events: { id: string; type: string; at: string; by: string; note?: string; from?: string; to?: string; part_count?: number; estimate?: string }[] };
type Part = { key: string; product: (BusinessEntity & { is_serialized?: boolean; track_batches?: boolean }) | null; qty: string; price: string; serials: string; batch?: string; warranty: boolean };
const transitionLabels: Record<string, string> = { diagnosing: 'Start diagnosis', awaiting_customer_approval: 'Request customer approval', approved: 'Record customer approval', in_repair: 'Start repair', awaiting_parts: 'Await parts', ready: 'Mark ready', delivered: 'Deliver device', unrepairable: 'Mark unrepairable', cancelled: 'Cancel and return device', received: 'Return to intake' };
export function ServiceDetail({ id, onClose, onChanged }: { id: string; onClose: () => void; onChanged: () => void }) {
  const session = useDashboardSession(); const can = (permission: string) => !!(session?.is_global || session?.permissions.includes(permission));
  const mutation = useWorkflowMutation(); const [detail, setDetail] = useState<Detail | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const [note, setNote] = useState(''); const [estimate, setEstimate] = useState(''); const [deposit, setDeposit] = useState(''); const [invoice, setInvoice] = useState<BusinessEntity | null>(null);
  const [parts, setParts] = useState<Part[]>([{ key: 'initial', product: null, qty: '', price: '0', serials: '', warranty: false }]); const [showParts, setShowParts] = useState(false);
  const dirty = !!note || showParts && parts.some(part => part.product || part.qty); useDraftProtection(dirty);
  const load = useCallback(async () => {
    setLoading(true); setError('');
    try { const res = await apiFetch(`/api/v1/service-requests/${id}`); const data = await res.json(); if (!res.ok) throw new Error(data.error?.message ?? 'Unable to load service request'); setDetail(data); setEstimate(data.estimated_amount); setDeposit(data.deposit_required); }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to load service request'); } finally { setLoading(false); }
  }, [id]);
  useEffect(() => { void load(); }, [load]);
  async function action(action: string, status?: string) {
    if (!note.trim()) { mutation.setError('Enter an action note, diagnosis, or evidence of customer approval.'); return; }
    if (action === 'estimate' && (estimate === '' || !Number.isFinite(Number(estimate)) || Number(estimate) < 0 || !Number.isFinite(Number(deposit)) || Number(deposit) < 0 || Number(deposit) > Number(estimate))) { mutation.setError('Enter a valid estimate and deposit.'); return; }
    if (action === 'link_sale' && !invoice) { mutation.setError('Select a posted service invoice.'); return; }
    if (status && !window.confirm(`${transitionLabels[status] ?? status}? ${['delivered', 'cancelled'].includes(status) ? 'Confirm device handover; consumed parts cost will be settled from repair WIP.' : 'This action will be recorded in service history.'}`)) return;
    const result = await mutation.mutate(`/api/v1/service-requests/${id}`, { action, status, note, estimated_amount: action === 'estimate' ? Number(estimate) : undefined, deposit_required_amount: action === 'estimate' ? Number(deposit) : undefined, service_sale_id: action === 'link_sale' ? invoice!.id : undefined });
    if (result) { setNote(''); setInvoice(null); toast.success('Service request updated.'); await load(); onChanged(); }
  }
  async function consume(event: React.FormEvent) {
    event.preventDefault(); if (parts.some(part => !part.product || Number(part.qty) <= 0 || !Number.isFinite(Number(part.qty)) || Number(part.price) < 0)) { mutation.setError('Complete every part and positive quantity.'); return; }
    if (!window.confirm('Consume these parts from the repair warehouse and post their cost to repair WIP?')) return;
    const result = await mutation.mutate(`/api/v1/service-requests/${id}/parts`, { items: parts.map(part => ({ product_id: part.product!.id, quantity: Number(part.qty), unit_price: Number(part.price), warranty_covered: part.warranty, batch_no: part.product?.track_batches ? part.batch?.trim() : undefined, serial_numbers: part.product?.is_serialized ? part.serials.split(/[\s,]+/).filter(Boolean) : undefined })) });
    if (result) { setShowParts(false); setParts([{ key: crypto.randomUUID(), product: null, qty: '', price: '0', serials: '', warranty: false }]); toast.success('Parts consumed and recorded.'); await load(); onChanged(); }
  }
  function updatePart(key: string, patch: Partial<Part>) { setParts(current => current.map(part => part.key === key ? { ...part, ...patch } : part)); }
  async function approve(decision: 'approved' | 'rejected') {
    if (!detail?.approval || !window.confirm(`${decision === 'approved' ? 'Approve' : 'Reject'} this service estimate?`)) return;
    const result = await mutation.mutate(`/api/v1/approvals/${detail.approval.id}/resolve`, { decision, reason: note || `Reviewed estimate ${detail.reference_no}` }); if (result) { setNote(''); await load(); toast.success('Estimate approval updated.'); }
  }
  return <Card><CardHeader className="flex flex-wrap flex-row justify-between gap-3"><CardTitle><h2>{detail?.reference_no ?? 'Service request'}</h2></CardTitle><div className="flex gap-2"><Button variant="outline" disabled={loading || mutation.pending} onClick={() => void load()}>Refresh details</Button><Button variant="outline" disabled={mutation.pending} onClick={() => { if (!dirty || window.confirm('Discard unsaved service notes and parts?')) onClose(); }}>Close details</Button></div></CardHeader><CardContent className="space-y-5">
    {loading ? <p role="status">Loading service request…</p> : null}{error || mutation.error ? <div role="alert" className="rounded-md border p-3">{error || mutation.error}{error ? <Button variant="outline" onClick={() => void load()}>Retry</Button> : null}</div> : null}
    {detail ? <><div className="flex flex-wrap gap-3"><Badge>{detail.status.replaceAll('_', ' ')}</Badge><span>{detail.service_type.replaceAll('_', ' ')} · {detail.branch.name} · {detail.warehouse?.name ?? 'No repair warehouse'}</span></div>
      <dl className="grid gap-4 sm:grid-cols-2"><div><dt className="text-sm text-muted-foreground">Customer / device</dt><dd>{detail.customer?.name ?? 'Walk-in'} · {detail.serial?.serialNumber ?? 'No registered serial'}</dd></div><div><dt className="text-sm text-muted-foreground">Estimate / approved / required deposit</dt><dd>{detail.estimated_amount} / {detail.approved_amount ?? 'Not approved'} / {detail.deposit_required}</dd></div><div><dt className="text-sm text-muted-foreground">Received</dt><dd>{new Date(detail.received_at).toLocaleString()}</dd></div><div><dt className="text-sm text-muted-foreground">Delivered</dt><dd>{detail.delivered_at ? new Date(detail.delivered_at).toLocaleString() : 'Not delivered'}</dd></div></dl>
      <section className="space-y-2"><h3 className="font-semibold">Issue and intake</h3><p className="whitespace-pre-wrap">{detail.issue}</p>{detail.intake_condition ? <p>Condition: {detail.intake_condition}</p> : null}{detail.accessories ? <p>Accessories: {detail.accessories}</p> : null}</section>
      <section className="space-y-3"><h3 className="font-semibold">Parts used</h3>{detail.parts.length ? <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th>Part</th><th>Quantity</th><th>Unit cost</th><th>Unit charge</th><th>Covered</th></tr></thead><tbody>{detail.parts.map(part => <tr key={part.id} className="border-b"><td className="py-3 pr-3">{part.product.name}</td><td>{part.quantity}</td><td>{part.unit_cost}</td><td>{part.unit_price}</td><td>{part.warranty_covered ? 'Warranty' : 'Billable'}</td></tr>)}</tbody></table></div> : <p className="text-muted-foreground">No parts consumed.</p>}
        {can('service.complete') && ['in_repair', 'awaiting_parts'].includes(detail.status) ? <Button variant="outline" disabled={mutation.pending} onClick={() => setShowParts(true)}>Consume parts</Button> : null}
        {showParts ? <form onSubmit={consume}><fieldset disabled={mutation.pending} className="space-y-3">{parts.map((part, index) => <div key={part.key} className="space-y-3 rounded-md border p-3"><div className="grid gap-3 sm:grid-cols-3"><EntityPicker label={`Service part ${index + 1}`} endpoint="/api/v1/products?is_active=true" value={part.product} onChange={product => updatePart(part.key, { product })} /><div><Label htmlFor={`part-qty-${part.key}`}>Part quantity {index + 1}</Label><Input id={`part-qty-${part.key}`} type="number" min={part.product?.is_serialized ? '1' : '0.0001'} step={part.product?.is_serialized ? '1' : '0.0001'} required value={part.qty} onChange={event => updatePart(part.key, { qty: event.target.value })} /></div><div><Label htmlFor={`part-price-${part.key}`}>Unit charge {index + 1}</Label><Input id={`part-price-${part.key}`} type="number" min="0" step="0.01" required value={part.price} onChange={event => updatePart(part.key, { price: event.target.value })} /></div></div>{part.product?.is_serialized ? <div><Label htmlFor={`part-serial-${part.key}`}>Part serials {index + 1}</Label><Textarea id={`part-serial-${part.key}`} required value={part.serials} onChange={event => updatePart(part.key, { serials: event.target.value })} /></div> : null}{part.product?.track_batches ? <div><Label htmlFor={`part-batch-${part.key}`}>Part batch {index + 1}</Label><Input id={`part-batch-${part.key}`} required value={part.batch ?? ''} onChange={event => updatePart(part.key, { batch: event.target.value })} /></div> : null}<label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={part.warranty} onChange={event => updatePart(part.key, { warranty: event.target.checked })} />Warranty covers this part</label><Button type="button" variant="outline" disabled={parts.length === 1} onClick={() => setParts(current => current.filter(item => item.key !== part.key))}>Remove part {index + 1}</Button></div>)}<div className="flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={() => setParts(current => [...current, { key: crypto.randomUUID(), product: null, qty: '', price: '0', serials: '', warranty: detail.service_type === 'warranty' }])}>Add part</Button><Button type="submit">Post parts consumption</Button><Button type="button" variant="outline" onClick={() => { if (!parts.some(part => part.product || part.qty) || window.confirm('Discard these unposted parts?')) setShowParts(false); }}>Cancel parts</Button></div></fieldset></form> : null}
      </section>
      {detail.service_sale ? <p>Service invoice: {can('sale.read') ? <a className="underline" target="_blank" rel="noreferrer" href={`/print/invoice/${detail.service_sale.id}`}>{detail.service_sale.referenceNo}</a> : detail.service_sale.referenceNo}</p> : null}
      {can('service.complete') ? <section className="space-y-4 border-t pt-4"><h3 className="font-semibold">Service actions</h3><fieldset disabled={mutation.pending} className="space-y-4"><div><Label htmlFor={`service-note-${id}`}>Action note / diagnosis / approval evidence</Label><Textarea id={`service-note-${id}`} value={note} maxLength={2000} onChange={event => setNote(event.target.value)} /></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => void action('note')}>Add service note</Button>{['received', 'diagnosing'].includes(detail.status) ? <Button variant="outline" onClick={() => void action('diagnosis')}>Save diagnosis</Button> : null}</div>
        {['received', 'diagnosing', 'awaiting_customer_approval'].includes(detail.status) ? <div className="grid items-end gap-3 sm:grid-cols-3"><div><Label htmlFor={`service-estimate-${id}`}>Service estimate</Label><Input id={`service-estimate-${id}`} type="number" min="0" step="0.01" value={estimate} onChange={event => setEstimate(event.target.value)} /></div><div><Label htmlFor={`service-deposit-${id}`}>Required deposit</Label><Input id={`service-deposit-${id}`} type="number" min="0" step="0.01" value={deposit} onChange={event => setDeposit(event.target.value)} /></div><Button variant="outline" onClick={() => void action('estimate')}>Save estimate</Button></div> : null}
        {!['delivered', 'cancelled'].includes(detail.status) && can('sale.read') ? <div className="space-y-3 rounded-md border p-3"><p className="text-sm">Bill service labour and installed parts through a service-only POS invoice for this customer and branch. Link it here; consumed parts must not be sold a second time.</p><EntityPicker label="Service invoice" endpoint={`/api/v1/sales?all_dates=true&status=completed&service_only=true&branch_id=${detail.branch.id}&customer_id=${detail.customer?.id ?? 'walk-in'}`} value={invoice} onChange={setInvoice} /><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => void action('link_sale')}>Link service invoice</Button>{can('sale.post') ? <Button variant="outline" asChild><Link href="/dashboard/pos">Open POS</Link></Button> : null}</div></div> : null}
        <div className="flex flex-wrap gap-2">{detail.available_transitions.map(status => <Button key={status} variant={status === 'cancelled' ? 'outline' : 'default'} onClick={() => void action('transition', status)}>{detail.service_type === 'warranty' && status === 'approved' ? 'Approve warranty repair' : transitionLabels[status] ?? status}</Button>)}</div>
      </fieldset>{detail.approval ? <div className="space-y-2"><p>Internal estimate approval: <Badge>{detail.approval.status}</Badge></p>{detail.approval.status === 'pending' && detail.approval.requestedBy !== session?.id && can('approval.resolve') ? <div className="flex gap-2"><Button disabled={mutation.pending} onClick={() => void approve('approved')}>Approve estimate</Button><Button variant="outline" disabled={mutation.pending} onClick={() => void approve('rejected')}>Reject estimate</Button></div> : null}</div> : null}</section> : null}
      <section className="space-y-3"><h3 className="font-semibold">Service history</h3><ol className="divide-y">{detail.events.map(event => <li key={event.id} className="space-y-1 py-3"><p className="font-medium">{event.type.replaceAll('_', ' ')}{event.to ? ` · ${event.from ?? 'New'} → ${event.to}` : ''}</p><p className="text-xs text-muted-foreground">{new Date(event.at).toLocaleString()} · {event.by}</p>{event.note ? <p className="whitespace-pre-wrap">{event.note}</p> : null}{event.part_count ? <p>{event.part_count} part lines consumed</p> : null}{event.estimate ? <p>Estimate: {event.estimate}</p> : null}</li>)}</ol></section>
    </> : null}
  </CardContent></Card>;
}
